# Generated by Django 4.0.3 on 2023-01-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_area_box_user_traffic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_area',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_tel',
        ),
    ]
