# Generated by Django 4.0.3 on 2023-01-18 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0003_remove_user_user_area_remove_user_user_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_role',
        ),
    ]
