# Generated by Django 4.0.3 on 2023-01-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0004_remove_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='traffic_text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
