# Generated by Django 4.0.3 on 2023-01-25 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traffic',
            name='traffic_area',
        ),
    ]
