# Generated by Django 4.0.3 on 2023-01-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_traffic_traffic_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traffic',
            name='traffic_num',
        ),
        migrations.AddField(
            model_name='traffic',
            name='traffic_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='traffic',
            name='traffic_text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
