# Generated by Django 4.0.3 on 2023-01-18 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_name', models.CharField(max_length=200)),
                ('box_area', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic.area')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('user_pwd', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('user_role', models.IntegerField()),
                ('user_area', models.CharField(max_length=200)),
                ('user_tel', models.CharField(max_length=200)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic.area')),
            ],
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traffic_num', models.IntegerField()),
                ('traffic_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('traffic_image2', models.ImageField(blank=True, null=True, upload_to='images2')),
                ('traffic_text', models.CharField(max_length=200)),
                ('traffic_second', models.IntegerField()),
                ('traffic_second2', models.IntegerField()),
                ('traffic_area', models.TextField()),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic.box')),
            ],
        ),
    ]
