# Generated by Django 4.0.3 on 2023-01-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0005_alter_traffic_traffic_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traffic',
            name='traffic_area',
        ),
        migrations.RemoveField(
            model_name='traffic',
            name='traffic_num',
        ),
        migrations.AddField(
            model_name='traffic',
            name='traffic_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
